/** App-stack catalog (from stack-picker APP_MODE). */
export const CATALOG_LAYERS: {
  slug: string
  name: string
  subtitle: string
  items: { slug: string; name: string; domain?: string }[]
}[] = [
  {
    slug: 'frontend',
    name: 'Frontend',
    subtitle: 'UI framework',
    items: [
      { slug: 'nextjs', name: 'Next.js', domain: 'nextjs.org' },
      { slug: 'react', name: 'React', domain: 'react.dev' },
      { slug: 'vue', name: 'Vue', domain: 'vuejs.org' },
      { slug: 'svelte', name: 'Svelte', domain: 'svelte.dev' },
      { slug: 'astro', name: 'Astro', domain: 'astro.build' },
      { slug: 'solidjs', name: 'SolidJS', domain: 'solidjs.com' },
      { slug: 'angular', name: 'Angular', domain: 'angular.dev' },
      { slug: 'remix', name: 'Remix', domain: 'remix.run' },
      { slug: 'nuxt', name: 'Nuxt', domain: 'nuxt.com' },
    ],
  },
  {
    slug: 'styling',
    name: 'Styling / UI',
    subtitle: 'Look & feel',
    items: [
      { slug: 'tailwind', name: 'Tailwind CSS', domain: 'tailwindcss.com' },
      { slug: 'shadcn', name: 'shadcn/ui', domain: 'ui.shadcn.com' },
      { slug: 'radix', name: 'Radix UI', domain: 'radix-ui.com' },
      { slug: 'chakra', name: 'Chakra UI', domain: 'chakra-ui.com' },
      { slug: 'mantine', name: 'Mantine', domain: 'mantine.dev' },
      { slug: 'mui', name: 'MUI', domain: 'mui.com' },
      { slug: 'bootstrap', name: 'Bootstrap', domain: 'getbootstrap.com' },
    ],
  },
  {
    slug: 'backend',
    name: 'Backend Runtime',
    subtitle: 'What runs your code',
    items: [
      { slug: 'nodejs', name: 'Node.js', domain: 'nodejs.org' },
      { slug: 'bun', name: 'Bun', domain: 'bun.sh' },
      { slug: 'deno', name: 'Deno', domain: 'deno.com' },
      { slug: 'python-fastapi', name: 'Python (FastAPI)', domain: 'fastapi.tiangolo.com' },
      { slug: 'go', name: 'Go', domain: 'go.dev' },
      { slug: 'rails', name: 'Ruby on Rails', domain: 'rubyonrails.org' },
      { slug: 'phoenix', name: 'Elixir / Phoenix', domain: 'phoenixframework.org' },
      { slug: 'nestjs', name: 'NestJS', domain: 'nestjs.com' },
      { slug: 'hono', name: 'Hono', domain: 'hono.dev' },
      { slug: 'dotnet', name: 'ASP.NET Core', domain: 'dotnet.microsoft.com' },
      { slug: 'spring', name: 'Spring Boot', domain: 'spring.io' },
    ],
  },
  {
    slug: 'hosting',
    name: 'Compute / Hosting',
    subtitle: 'Where it lives',
    items: [
      { slug: 'vercel', name: 'Vercel', domain: 'vercel.com' },
      { slug: 'cloudflare-workers', name: 'Cloudflare Workers', domain: 'cloudflare.com' },
      { slug: 'aws-lambda', name: 'AWS Lambda', domain: 'aws.amazon.com' },
      { slug: 'aws-ec2', name: 'AWS EC2', domain: 'aws.amazon.com' },
      { slug: 'gcp-run', name: 'Google Cloud Run', domain: 'cloud.google.com' },
      { slug: 'azure-app', name: 'Azure App Service', domain: 'azure.microsoft.com' },
      { slug: 'fly', name: 'Fly.io', domain: 'fly.io' },
      { slug: 'railway', name: 'Railway', domain: 'railway.app' },
      { slug: 'render', name: 'Render', domain: 'render.com' },
      { slug: 'netlify', name: 'Netlify', domain: 'netlify.com' },
      { slug: 'digitalocean', name: 'DigitalOcean', domain: 'digitalocean.com' },
      { slug: 'cloudflare-pages', name: 'Cloudflare Pages', domain: 'cloudflare.com' },
    ],
  },
  {
    slug: 'database',
    name: 'Database',
    subtitle: 'Where data sleeps',
    items: [
      { slug: 'postgres', name: 'PostgreSQL', domain: 'postgresql.org' },
      { slug: 'neon', name: 'Neon', domain: 'neon.tech' },
      { slug: 'supabase', name: 'Supabase', domain: 'supabase.com' },
      { slug: 'planetscale', name: 'PlanetScale', domain: 'planetscale.com' },
      { slug: 'mysql', name: 'MySQL', domain: 'mysql.com' },
      { slug: 'mongodb', name: 'MongoDB', domain: 'mongodb.com' },
      { slug: 'firebase', name: 'Firebase', domain: 'firebase.google.com' },
      { slug: 'dynamodb', name: 'DynamoDB', domain: 'aws.amazon.com' },
      { slug: 'convex', name: 'Convex', domain: 'convex.dev' },
      { slug: 'turso', name: 'Turso', domain: 'turso.tech' },
      { slug: 'd1', name: 'Cloudflare D1', domain: 'cloudflare.com' },
      { slug: 'redis', name: 'Redis', domain: 'redis.io' },
    ],
  },
  {
    slug: 'orm',
    name: 'ORM / Data Layer',
    subtitle: 'How you query',
    items: [
      { slug: 'prisma', name: 'Prisma', domain: 'prisma.io' },
      { slug: 'drizzle', name: 'Drizzle', domain: 'orm.drizzle.team' },
      { slug: 'kysely', name: 'Kysely', domain: 'kysely.dev' },
      { slug: 'typeorm', name: 'TypeORM', domain: 'typeorm.io' },
      { slug: 'sequelize', name: 'Sequelize', domain: 'sequelize.org' },
      { slug: 'raw-sql', name: 'Raw SQL', domain: 'postgresql.org' },
    ],
  },
  {
    slug: 'auth',
    name: 'Auth',
    subtitle: "Who's logging in",
    items: [
      { slug: 'clerk', name: 'Clerk', domain: 'clerk.com' },
      { slug: 'auth0', name: 'Auth0', domain: 'auth0.com' },
      { slug: 'supabase-auth', name: 'Supabase Auth', domain: 'supabase.com' },
      { slug: 'authjs', name: 'Auth.js (NextAuth)', domain: 'authjs.dev' },
      { slug: 'workos', name: 'WorkOS', domain: 'workos.com' },
      { slug: 'firebase-auth', name: 'Firebase Auth', domain: 'firebase.google.com' },
      { slug: 'better-auth', name: 'Better Auth', domain: 'better-auth.com' },
      { slug: 'cognito', name: 'AWS Cognito', domain: 'aws.amazon.com' },
    ],
  },
  {
    slug: 'storage',
    name: 'File / Blob Storage',
    subtitle: 'Big binary stuff',
    items: [
      { slug: 's3', name: 'AWS S3', domain: 'aws.amazon.com' },
      { slug: 'r2', name: 'Cloudflare R2', domain: 'cloudflare.com' },
      { slug: 'vercel-blob', name: 'Vercel Blob', domain: 'vercel.com' },
      { slug: 'gcs', name: 'Google Cloud Storage', domain: 'cloud.google.com' },
      { slug: 'azure-blob', name: 'Azure Blob', domain: 'azure.microsoft.com' },
      { slug: 'uploadthing', name: 'UploadThing', domain: 'uploadthing.com' },
      { slug: 'supabase-storage', name: 'Supabase Storage', domain: 'supabase.com' },
    ],
  },
  {
    slug: 'monitoring',
    name: 'Monitoring / APM',
    subtitle: 'Is it on fire?',
    items: [
      { slug: 'sentry', name: 'Sentry', domain: 'sentry.io' },
      { slug: 'datadog', name: 'Datadog', domain: 'datadoghq.com' },
      { slug: 'newrelic', name: 'New Relic', domain: 'newrelic.com' },
      { slug: 'grafana', name: 'Grafana', domain: 'grafana.com' },
      { slug: 'honeycomb', name: 'Honeycomb', domain: 'honeycomb.io' },
      { slug: 'axiom', name: 'Axiom', domain: 'axiom.co' },
      { slug: 'better-stack', name: 'Better Stack', domain: 'betterstack.com' },
    ],
  },
  {
    slug: 'product-analytics',
    name: 'Product Analytics',
    subtitle: 'What users actually do',
    items: [
      { slug: 'posthog', name: 'PostHog', domain: 'posthog.com' },
      { slug: 'amplitude', name: 'Amplitude', domain: 'amplitude.com' },
      { slug: 'mixpanel', name: 'Mixpanel', domain: 'mixpanel.com' },
      { slug: 'heap', name: 'Heap', domain: 'heap.io' },
      { slug: 'june', name: 'June', domain: 'june.so' },
      { slug: 'statsig', name: 'Statsig', domain: 'statsig.com' },
    ],
  },
  {
    slug: 'web-analytics',
    name: 'Web Analytics',
    subtitle: 'Pageviews & vitals',
    items: [
      { slug: 'ga', name: 'Google Analytics', domain: 'marketingplatform.google.com' },
      { slug: 'plausible', name: 'Plausible', domain: 'plausible.io' },
      { slug: 'fathom', name: 'Fathom', domain: 'usefathom.com' },
      { slug: 'simple-analytics', name: 'Simple Analytics', domain: 'simpleanalytics.com' },
      { slug: 'vercel-analytics', name: 'Vercel Analytics', domain: 'vercel.com' },
      { slug: 'cf-analytics', name: 'Cloudflare Analytics', domain: 'cloudflare.com' },
    ],
  },
  {
    slug: 'email',
    name: 'Transactional Email',
    subtitle: 'Reset links & receipts',
    items: [
      { slug: 'resend', name: 'Resend', domain: 'resend.com' },
      { slug: 'postmark', name: 'Postmark', domain: 'postmarkapp.com' },
      { slug: 'sendgrid', name: 'SendGrid', domain: 'sendgrid.com' },
      { slug: 'ses', name: 'AWS SES', domain: 'aws.amazon.com' },
      { slug: 'mailgun', name: 'Mailgun', domain: 'mailgun.com' },
      { slug: 'loops', name: 'Loops', domain: 'loops.so' },
    ],
  },
  {
    slug: 'payments',
    name: 'Payments',
    subtitle: 'Take the money',
    items: [
      { slug: 'stripe', name: 'Stripe', domain: 'stripe.com' },
      { slug: 'lemonsqueezy', name: 'Lemon Squeezy', domain: 'lemonsqueezy.com' },
      { slug: 'paddle', name: 'Paddle', domain: 'paddle.com' },
      { slug: 'polar', name: 'Polar', domain: 'polar.sh' },
      { slug: 'paypal', name: 'PayPal', domain: 'paypal.com' },
    ],
  },
  {
    slug: 'ai',
    name: 'AI / LLM',
    subtitle: 'The smart bits',
    items: [
      { slug: 'anthropic', name: 'Anthropic Claude', domain: 'anthropic.com' },
      { slug: 'openai', name: 'OpenAI', domain: 'openai.com' },
      { slug: 'gemini', name: 'Google Gemini', domain: 'ai.google.dev' },
      { slug: 'vercel-ai', name: 'Vercel AI Gateway', domain: 'vercel.com' },
      { slug: 'replicate', name: 'Replicate', domain: 'replicate.com' },
      { slug: 'together', name: 'Together AI', domain: 'together.ai' },
      { slug: 'groq', name: 'Groq', domain: 'groq.com' },
    ],
  },
  {
    slug: 'search',
    name: 'Search',
    subtitle: 'Find stuff fast',
    items: [
      { slug: 'algolia', name: 'Algolia', domain: 'algolia.com' },
      { slug: 'meilisearch', name: 'Meilisearch', domain: 'meilisearch.com' },
      { slug: 'typesense', name: 'Typesense', domain: 'typesense.org' },
      { slug: 'elastic', name: 'Elastic', domain: 'elastic.co' },
      { slug: 'postgres-fts', name: 'Postgres FTS', domain: 'postgresql.org' },
    ],
  },
  {
    slug: 'cms',
    name: 'CMS / Content',
    subtitle: 'Marketing & blog',
    items: [
      { slug: 'sanity', name: 'Sanity', domain: 'sanity.io' },
      { slug: 'contentful', name: 'Contentful', domain: 'contentful.com' },
      { slug: 'payload', name: 'Payload', domain: 'payloadcms.com' },
      { slug: 'strapi', name: 'Strapi', domain: 'strapi.io' },
      { slug: 'notion-cms', name: 'Notion', domain: 'notion.so' },
      { slug: 'mdx', name: 'Markdown / MDX', domain: 'mdxjs.com' },
    ],
  },
  {
    slug: 'cicd',
    name: 'CI / CD',
    subtitle: 'Ship it',
    items: [
      { slug: 'gh-actions', name: 'GitHub Actions', domain: 'github.com' },
      { slug: 'vercel-deploys', name: 'Vercel Deploys', domain: 'vercel.com' },
      { slug: 'circleci', name: 'CircleCI', domain: 'circleci.com' },
      { slug: 'gitlab-ci', name: 'GitLab CI', domain: 'gitlab.com' },
      { slug: 'buildkite', name: 'Buildkite', domain: 'buildkite.com' },
    ],
  },
]
